Initial commit by Vortex

diff --git a/lib/ghost b/lib/ghost
--- a/lib/ghost
+++ b/lib/ghost
@@ -1,5 +1,8 @@
 #!/usr/bin/env bash
 
+# cd into the project directory because we need to be inside a git repo
+cd $HOME/vortex_project || { echo "Error: Could not find project directory"; exit 1; }
+
 # File with the channel webhook for where to send the notification
 CONFIG_FILE="$HOME/.vortex_config"
 
@@ -7,8 +10,10 @@ CONFIG_FILE="$HOME/.vortex_config"
 if [[ -f "$CONFIG_FILE" ]]; then
     source "$CONFIG_FILE"
 else
-    echo "Error: Webhook not configured in $CONFIG_FILE"
-    exit 1
+    echo "Discord webhook not configured in $CONFIG_FILE"
+    read -p "Please enter your Discord webhook URL: " user_d_webhook
+    echo "VORTEX_D_WEBHOOK=\"$user_d_webhook\"" > "$CONFIG_FILE"
+    VORTEX_D_WEBHOOK="$user_d_webhook"
 fi
 
 # Temp file to store the notified count so it's not lost after systemd ends
@@ -17,7 +22,7 @@ inserts_num_file="/tmp/vortex_ghost_state$(whoami)"
 # Global variable that stores the last count where the user was given a notification in a file
 last_notified_count=$(cat "$inserts_num_file" 2> /dev/null || echo 0)
 
-# Get number of insertions and deletions in a project directory
+# Get number of insertions and deletions in a git project directory
 num_of_mods_in_dir(){
     local num_of_mod_lines=$(git diff --shortstat)
     num_of_inserts=0
@@ -37,7 +42,7 @@ num_of_mods_in_dir	# call the function
 # Send notification msg to discord channel if the user made 50+ insertions
 send_commit_ntf(){
     if [[ "$num_of_inserts" -ge 50 && "$num_of_inserts" -gt "$last_notified_count" ]]; then
-        curl -X POST "$VORTEX_WEBHOOK" \
+        curl -X POST "$VORTEX_D_WEBHOOK" \
         -H "Content-Type: application/json" \
         -d "{\"content\": \"Number of Inserts: $num_of_inserts \n Number of Deletions: $num_of_deletes\"}"
 	echo "$num_of_inserts" > "$inserts_num_file"
